server:
  port: 8086

spring:
  application:
    name: auth-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400