
version: "3"
services:
  elasticsearch:
    ports:
      - 0.0.0.0:9200:9200/tcp
    expose:
      - 9200/tcp
      - 9300/tcp
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ELASTIC_CONTAINER=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    command: eswrapper
