
version: "3"
services:
  mongodb-community-server:
    container_name: mongodb1
    ports:
      - 0.0.0.0:27017:27017/tcp
    expose:
      - 27017/tcp
    user: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=admin
    image: mongodb/mongodb-community-server:latest
